"""add replaced_course_id to manual fulfillments

Revision ID: 14a4a805abd2
Revises: e5f6a7b8c9d0
Create Date: 2026-07-26 15:29:41.472899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a4a805abd2'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_requirement_fulfillments', sa.Column('replaced_course_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_requirement_fulfillments', 'replaced_course_id')
    # ### end Alembic commands ###
