"""init

Revision ID: 75897d45469e
Revises: 
Create Date: 2026-07-19 08:57:13.809443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75897d45469e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('course_number', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('credit_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('course_id', name=op.f('pk_courses')),
    sa.UniqueConstraint('subject', 'course_number', name='uq_courses_subject_course_number')
    )
    op.create_index(op.f('ix_courses_course_number'), 'courses', ['course_number'], unique=False)
    op.create_index(op.f('ix_courses_subject'), 'courses', ['subject'], unique=False)
    op.create_table('terms',
    sa.Column('term_code', sa.String(length=6), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('term_code', name=op.f('pk_terms'))
    )
    op.create_table('link_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=6), nullable=False),
    sa.Column('external_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_link_groups_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_code'], ['terms.term_code'], name=op.f('fk_link_groups_term_code_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_groups')),
    sa.UniqueConstraint('course_id', 'term_code', 'external_code', name='uq_link_groups_course_term_code')
    )
    op.create_index(op.f('ix_link_groups_course_id'), 'link_groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_link_groups_term_code'), 'link_groups', ['term_code'], unique=False)
    op.create_table('sections',
    sa.Column('crn', sa.String(length=10), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=6), nullable=False),
    sa.Column('section_number', sa.String(length=10), nullable=False),
    sa.Column('link_identifier', sa.String(length=50), nullable=True),
    sa.Column('is_linked', sa.Boolean(), nullable=False),
    sa.Column('link_group_id', sa.Integer(), nullable=True),
    sa.Column('link_slot', sa.String(length=50), nullable=True),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.Column('max_enrollment', sa.Integer(), nullable=True),
    sa.Column('enrollment', sa.Integer(), nullable=True),
    sa.Column('instructor', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('fk_sections_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_group_id'], ['link_groups.id'], name=op.f('fk_sections_link_group_id_link_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_code'], ['terms.term_code'], name=op.f('fk_sections_term_code_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('crn', name=op.f('pk_sections'))
    )
    op.create_index(op.f('ix_sections_course_id'), 'sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_sections_link_group_id'), 'sections', ['link_group_id'], unique=False)
    op.create_index(op.f('ix_sections_term_code'), 'sections', ['term_code'], unique=False)
    op.create_table('meeting_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crn', sa.String(length=10), nullable=False),
    sa.Column('meeting_type', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['crn'], ['sections.crn'], name=op.f('fk_meeting_times_crn_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_times'))
    )
    op.create_index(op.f('ix_meeting_times_crn'), 'meeting_times', ['crn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_times_crn'), table_name='meeting_times')
    op.drop_table('meeting_times')
    op.drop_index(op.f('ix_sections_term_code'), table_name='sections')
    op.drop_index(op.f('ix_sections_link_group_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_course_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_link_groups_term_code'), table_name='link_groups')
    op.drop_index(op.f('ix_link_groups_course_id'), table_name='link_groups')
    op.drop_table('link_groups')
    op.drop_table('terms')
    op.drop_index(op.f('ix_courses_subject'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_number'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
